Minor updates to documentation
open-ephys/onix-bonsai-onix1 pull request #189
Opened 2024-08-02 15:13 UTC by jonnew

- Clarification and typo fixes

2024-08-02 20:42 UTC, bparks13 requested changes
Looks good, I'll go ahead and implement the change listed and then we can merge the PR

2024-08-02 20:42 UTC, bparks13 commented on OpenEphys.Onix1/MultiDeviceFactory.cs
> +    /// an ONI hub can be omitted from a device group to aid it useability (e.g. <see cref="ConfigureBreakoutBoard"/>).
```suggestion
    /// an ONI hub can be omitted from a device group to aid its useability (e.g. <see cref="ConfigureBreakoutBoard"/>).
```

2024-08-02 20:43 UTC, bparks13 approved these changes

2024-08-02 20:50 UTC, merged

2024-08-02 20:59 UTC, glopesdev commented on OpenEphys.Onix1/MultiDeviceFactory.cs
> +    /// registering logical groups of <see cref="oni.Device"/>s.
This somehow seems now less clear, since it makes it seem the operator is registering the group rather than each individual device. Maybe we shouldn't talk about "device table" since that is a hardware specific concept, but mentioning that there is a context "device manager" might be important so people understand why sometimes the drop down shows devices and sometimes not.

2024-08-02 20:59 UTC, glopesdev commented on OpenEphys.Onix1/MultiDeviceFactory.cs
> +    /// This class allows configuration of logical device groups of <see cref="oni.Device"/>s across ONI-defined
```suggestion
    /// This class allows configuration of logical groups of <see cref="oni.Device"/>s across ONI-defined
```

2024-08-02 20:59 UTC, glopesdev commented on OpenEphys.Onix1/MultiDeviceFactory.cs
> +        /// Gets or sets a unique device group name.
Could be useful to clarify here that this name is used as a prefix for individual device names in the group.

2024-08-04 15:32 UTC, jonnew commented on OpenEphys.Onix1/MultiDeviceFactory.cs
> +    /// registering logical groups of <see cref="oni.Device"/>s.
Really, as far as I see, we are both wrong. 
- Device table is hardware-agnostic, its required by the ONI API regardless of hardware
- This class does not configure aggregates of oni.Devices (nullifying impact of last bullet), but OpenEphys.Onix1's concept of device, which is much looser (e.g. any dev using passthrough)

I m going to remove references to oni.Devices because its just not correct. I agree with Device manager comment ill try to add some text.