Add Acquisition or Configuration category to public properties
open-ephys/onix-bonsai-onix1 pull request #226
Opened 2024-08-20 14:04 UTC by bparks13

To ensure a consistent user experience across all operators, this PR adds a string to the Category attribute for all public properties that defines the property as either `Acquisition` or `Configuration`.

`Configuration` properties are set prior to the start of the workflow. These are not updated in real-time, and are configured once when the workflow starts.

`Acquisition` properties can have an initial state defined before the workflow begins, but they can be updated in real-time with new values sent to hardware while the workflow is running.

2024-08-20 18:11 UTC, jonnew requested changes
Can you do a quick review of all these changes and make sure that they comport with my commands on `MutliDeviceFactory.Name`? Basically, a property should be marked if its something exposed to the user that changes the behavior of a device at start or start/runtime. Anything outside of that scope should not be marked.

Aside from this, in `ConfigureBreakoutAnalogIO` the direction properties are all marked as Acquisition, but should be configuration. Thats left over from when they were settable at runtime and I forgot to change.

2024-08-20 18:11 UTC, jonnew commented on OpenEphys.Onix1/ConfigureNeuropixelsV2eLinkController.cs
> -
What changed here?

2024-08-20 18:13 UTC, bparks13 commented on OpenEphys.Onix1/ConfigureNeuropixelsV2eLinkController.cs
> -
There was an empty line that I removed, no functional changes

2024-08-20 18:16 UTC, bparks13 commented on OpenEphys.Onix1/MultiDeviceFactory.cs
> +        [Category(ConfigurationCategory)]
I had modified these because they are shown to user from the headstage and they set the name for all subsequent devices before the workflow begins and are not modified in real-time. In my mind, the aggregate name is a Configuration property for that reason.

Plus, if we don't mark these with a category, they get lumped into a `Misc` category. So for consistency everything that is exposed to the user got a category attribute.

2024-08-20 18:29 UTC, bparks13 commented on OpenEphys.Onix1/MultiDeviceFactory.cs
> +        [Category(ConfigurationCategory)]
re: marking the setter as private.

Tested this locally, it throws the following error when opening a workflow with an aggregate:
![image](https://github.com/user-attachments/assets/c0738396-f0b0-4d9e-a614-3cf4940c38ba)

2024-08-21 17:13 UTC, jonnew commented on OpenEphys.Onix1/MultiDeviceFactory.cs
> +        [Category(ConfigurationCategory)]
ok, so I was wrong on all accounts :). Not the first time.

2024-08-21 17:28 UTC, jonnew commented
The remaining though i have before merging is the members of a `MultiDeviceFactory` being marked as `Configuration`

![image](https://github.com/user-attachments/assets/f6bf9e1e-ad3a-430a-a402-068b9050599c)

I understand the reasoning here, as the properties referred to by the attribute are indeed `Configuration` level. But really the user is going to be manipulating the inner properties of the devices, which can be both `Acquisition` or `Configuration`. These are not shown in the current property pane, but the point kinda still stands.

I think a way around this to define another category defintion

    public abstract class DeviceFactory : Sink<ContextTask>
    {
        internal const string ConfigurationCategory = "Configuration";
        internal const string AcquisitionCategory = "Acquisition";
        internal const string DevicesCategory = "Devices";

        internal abstract IEnumerable<IDeviceConfiguration> GetDevices();
    }

which can be used for member devices of `MultiDeviceFactory`s

![image](https://github.com/user-attachments/assets/61aedb06-8277-4bb2-b029-a73fcec3ff3b)

The `Devices` name is up for suggestions.

2024-08-21 17:36 UTC, bparks13 commented
I am in favor of adding `Devices` as a category, I was just looking at the docs to see how we refer to these; they are classified as `Device Configuration Operators`, and we refer to them as devices from the aggregate level.

My only caveat with adding this category is that @cjsha and I were discussing what to name the headings in the aggregate page (for instance, [`ConfigureBreakoutBoard`](https://open-ephys.github.io/onix1-bonsai-docs/api/OpenEphys.Onix1.ConfigureBreakoutBoard.html)). Currently they are listed as `Properties`, but if we add this new category I would argue that we change the heading to match it, since the subheadings are the devices.

2024-08-22 15:30 UTC, jonnew commented
@bparks13 I agree with all. I feel a small force against this because in the ONI standard, `device` has very particular meaning. However, the ONI standard does not get to uniformly define what a device is for all its possible uses. In the context of this library, its very useful to refer to these leaf objects as devices, so let's do that.

2024-08-22 20:12 UTC, jonnew approved these changes

2024-08-22 20:12 UTC, jonnew commented on OpenEphys.Onix1/Headstage64OpticalStimulatorTrigger.cs
>              get => burstsPerTrain.Value;
(Cant put comment where i want to)
`BurstCurrent` is classified as "Misc". Although it can change in real time, I think i like the fact that is not in the acquisition category since it is readonly.

2024-08-22 20:29 UTC, bparks13 commented on OpenEphys.Onix1/Headstage64OpticalStimulatorTrigger.cs
>              get => burstsPerTrain.Value;
Agreed, I actually almost put it as `Acquisition`, but for the same reason of it being readonly i left it as Misc

2024-08-22 20:30 UTC, merged